version: "3"

services:
  api:
    build: ./
    image: urlshortener
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - ./env_example
    volumes:
      - "db_volume:/data"
volumes:
  db_volume:
